// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID              int32            `db:"id" json:"id"`
	PatientID       *int32           `db:"patient_id" json:"patient_id"`
	DoctorID        *int32           `db:"doctor_id" json:"doctor_id"`
	AppointmentDate pgtype.Timestamp `db:"appointment_date" json:"appointment_date"`
	Status          *string          `db:"status" json:"status"`
	Notes           *string          `db:"notes" json:"notes"`
	Diagnosis       *string          `db:"diagnosis" json:"diagnosis"`
	TreatmentPlan   *string          `db:"treatment_plan" json:"treatment_plan"`
	CreatedBy       *int32           `db:"created_by" json:"created_by"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Patient struct {
	ID                    int32            `db:"id" json:"id"`
	FirstName             string           `db:"first_name" json:"first_name"`
	LastName              string           `db:"last_name" json:"last_name"`
	Email                 *string          `db:"email" json:"email"`
	Phone                 *string          `db:"phone" json:"phone"`
	DateOfBirth           pgtype.Date      `db:"date_of_birth" json:"date_of_birth"`
	Gender                *string          `db:"gender" json:"gender"`
	Address               *string          `db:"address" json:"address"`
	MedicalHistory        *string          `db:"medical_history" json:"medical_history"`
	Allergies             *string          `db:"allergies" json:"allergies"`
	EmergencyContactName  *string          `db:"emergency_contact_name" json:"emergency_contact_name"`
	EmergencyContactPhone *string          `db:"emergency_contact_phone" json:"emergency_contact_phone"`
	CreatedBy             *int32           `db:"created_by" json:"created_by"`
	CreatedAt             pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID           int32            `db:"id" json:"id"`
	Email        string           `db:"email" json:"email"`
	PasswordHash string           `db:"password_hash" json:"password_hash"`
	Role         string           `db:"role" json:"role"`
	FirstName    string           `db:"first_name" json:"first_name"`
	LastName     string           `db:"last_name" json:"last_name"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
