// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"
)

type Querier interface {
	CountAppointments(ctx context.Context) (int64, error)
	CountAppointmentsByStatus(ctx context.Context, status *string) (int64, error)
	CountPatients(ctx context.Context) (int64, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (*Appointment, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (*Patient, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteAppointment(ctx context.Context, id int32) error
	DeletePatient(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetAppointmentByID(ctx context.Context, id int32) (*GetAppointmentByIDRow, error)
	GetAppointments(ctx context.Context, arg GetAppointmentsParams) ([]*GetAppointmentsRow, error)
	GetAppointmentsByDateRange(ctx context.Context, arg GetAppointmentsByDateRangeParams) ([]*GetAppointmentsByDateRangeRow, error)
	GetAppointmentsByDoctor(ctx context.Context, arg GetAppointmentsByDoctorParams) ([]*GetAppointmentsByDoctorRow, error)
	GetDoctors(ctx context.Context) ([]*GetDoctorsRow, error)
	GetPatientAppointments(ctx context.Context, patientID *int32) ([]*GetPatientAppointmentsRow, error)
	GetPatientByID(ctx context.Context, id int32) (*Patient, error)
	GetPatients(ctx context.Context, arg GetPatientsParams) ([]*Patient, error)
	GetTodaysAppointments(ctx context.Context) ([]*GetTodaysAppointmentsRow, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id int32) (*User, error)
	SearchPatients(ctx context.Context, arg SearchPatientsParams) ([]*Patient, error)
	UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (*Appointment, error)
	UpdatePatient(ctx context.Context, arg UpdatePatientParams) (*Patient, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
